### ISSUE TITLE
Use of non existing dependencies

### ISSUE THREAD

**Issue by BugDiver** [jcustenborder/docker-compose-junit-extension#13]
This module uses a dependency from `com.palantir.docker.compose:docker-compose-rule-core:jar:0.34.0` which is hosted on bintray. As of now, the bintray support is stopped by JFrog, making the dep inaccessible.

This issue is causing upstream projects (kafka-twitter-connect) to not to able to build from the source. 

Maybe the dep repo can be forked and publish to maven central just like other modules to make it accessible.

**Comment by kathicks** [comment]
Experiencing the same issue.

Tried to build [kafka-connect-twitter](https://github.com/jcustenborder/kafka-connect-twitter) and am getting an error stating: `Access denied to: https://dl.bintray.com/palantir/releases/com/palantir/docker/compose/docker-compose-rule-core/0.34.0/docker-compose-rule-core-0.34.0.pom`

**Comment by jcustenborder** [comment]
@BugDiver @kathicks This has already been corrected in this repo. kafka-connect-twitter hasn't been updated with a parent pom that would correct the issue. Do you all mind taking a look at [2.8.0-1](https://github.com/jcustenborder/kafka-connect-twitter/tree/2.8.0-1) of kafka-connect-twitter and giving me feedback?

**Comment by kathicks** [comment]
Thanks, @jcustenborder. Just checked out the `2.8.0-1` branch of `kafka-connect-twitter` and was able to build it successfully.

Thanks for resolving - really appreciated!

**Comment by jcustenborder** [comment]
Awesome! @kathicks Can you give your built version a quick test and make sure it's working ok? Then I'll push the change to master, and redeploy to the Confluent Hub

**Comment by kathicks** [comment]
Thanks, @jcustenborder!

Am a bit of a newcomer to Kafka, so don't have loads of knowledge to know whether all is working as expected - but worked through some of [this tutorial](https://www.confluent.io/blog/using-ksql-to-analyse-query-and-transform-data-in-kafka/) and that all seems to have worked okay.

**Comment by jcustenborder** [comment]
Ahh perfect! Good ol' Robin. I'll go ahead and push the changes. Thank you!
